In [205]:
import pandas as pd
import numpy as np

#credits = pd.read_csv("Jeux_de_donnees\movies_dataset\credits.csv")
movies_metadata = pd.read_csv("Jeux_de_donnees\movies_dataset\movies_metadata.csv")

movies_metadata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3437: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [206]:
#movies_metadata['budget']=movies_metadata['budget'].astype('float')

def to_float(x):
    if x.isnumeric():
        x = float(x)
    else:
        x = np.nan
    return x

movies_metadata['budget']=movies_metadata['budget'].apply(to_float)
movies_metadata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45463 non-null  float64
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(5), object(19)
memory usage: 8.3+ MB

In [207]:
movies_metadata.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0.0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0.0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [208]:
movies_metadata['release_date'] = pd.to_datetime(movies_metadata['release_date'], errors='coerce')
movies_metadata['year'] = movies_metadata['release_date'].apply(
    lambda x: str(x).split('-')[0] if x !=np.nan else np.nan)

# 1.Système de recommandation simpliste
#### Recommandation en fonction de la note moyenne : Doit-on donné la même importance à deux films ayant la même note mais avec un nombre de votant considérablement différent ?
#### On va plutôt chercher à normaliser la note moyenne par rapport au nombre de votant, c'est à dire donner plus d'importance au note ayant le plus de votant.
#### Formule de la note pondérée :
<img src="img\norm_imdb.png" width="600">

- r la note moyenne
- v le nombre de vote
- m le nombre minimum de vote pour apparaitre dans la liste
- c la valeur moyenne du nombre de vote

## On calcule le nombre de votes recueillis par le film du 80ème centile

#### Quel est la note de film qui me permet de séparer les 20% des films les mieux noté des 80% le moins bien noté ?

In [209]:
m = movies_metadata['vote_count'].quantile(0.80)
movies_metadata['vote_count'].quantile(0.80)

50.0

#### On ne concerve que les films de plus de 45 min et de moins de 300 minutes

In [210]:
q_film = movies_metadata[(movies_metadata['runtime'] >= 45) & (movies_metadata['runtime'] <= 300)]

#### On ne concerve que le films qui on recueillis plus de m votes (on veut que le film soit populaire pour être recommandé)

In [211]:
q_film = movies_metadata[(movies_metadata['vote_count'] >= m)]

In [212]:
q_film.shape

(9151, 25)

#### On calcule le score c

In [213]:
c = movies_metadata['vote_average'].mean()
c

5.618207215133889

#### On va enfin pouvoir calculer la note pondéré

In [214]:
def note_ponderee(x, m=m, c=c):
    v = x['vote_count']
    r = x['vote_average']
    return ((v/(v+m)*r)+(m/m+v)*c)

In [215]:
q_film['score'] = q_film.apply(note_ponderee, axis=1)

<ipython-input-215-140611d3c3d2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q_film['score'] = q_film.apply(note_ponderee, axis=1)

In [216]:
q_film = q_film.sort_values('score', ascending=False)
les30film_a_recomander = q_film[['title', 'vote_count', 'vote_average', 'score', 'runtime']].head(30)

In [217]:
les30film_a_recomander

,title,vote_count,vote_average,score,runtime
15480,Inception,14075.0,8.1,79089.956088,148.0
12481,The Dark Knight,12269.0,8.3,68943.668842,152.0
14551,Avatar,12114.0,7.2,68071.750816,162.0
17818,The Avengers,12000.0,7.4,67431.474083,143.0
26564,Deadpool,11444.0,7.4,64307.749386,108.0
22879,Interstellar,11187.0,8.1,62864.566281,169.0
20051,Django Unchained,10297.0,7.8,57864.060209,165.0
23753,Guardians of the Galaxy,10014.0,7.9,56274.206011,121.0
2843,Fight Club,9678.0,8.3,54386.884975,139.0
18244,The Hunger Games,9634.0,6.9,54138.290892,142.0
26553,Mad Max: Fury Road,9629.0,7.3,54110.597771,120.0
18252,The Dark Knight Rises,9263.0,7.6,52054.630838,165.0
2458,The Matrix,9079.0,7.9,51021.178245,136.0
12588,Iron Man,8951.0,7.4,50301.549883,126.0
20830,Iron Man 3,8951.0,6.8,50300.953216,130.0
4863,The Lord of the Rings: The Fellowship of the Ring,8892.0,8.0,49970.672031,178.0
25084,Jurassic World,8842.0,6.5,49688.269854,124.0
292,Pulp Fiction,8670.0,8.3,48723.727171,154.0
19971,The Hobbit: An Unexpected Journey,8427.0,7.0,47357.209121,169.0
314,The Shawshank Redemption,8358.0,8.5,46971.043564,142.0
7000,The Lord of the Rings: The Return of the King,8226.0,8.1,46229.041822,201.0
351,Forrest Gump,8147.0,8.2,45785.302371,142.0
26555,Star Wars: The Force Awakens,7993.0,7.5,44919.401853,136.0
1639,Titanic,7770.0,7.5,43666.540315,194.0
19261,Skyfall,7718.0,6.9,43373.797081,143.0
30543,Suicide Squad,7717.0,5.9,43367.185305,123.0
5814,The Lord of the Rings: The Two Towers,7641.0,8.0,42942.287529,179.0
10122,Batman Begins,7511.0,7.5,42211.423003,140.0
26567,Captain America: Civil War,7462.0,7.1,41935.733189,147.0
30051,The Martian,7442.0,7.6,41823.865581,141.0

# 2. Recommandation basé sur les connaissances

#### On va demander à l'utilisateur de rensiegner certaine information sur ces préférences de films :
- Les genres de films qu'il recherche
- la durée
- la chronologie des films recommandés (s'il préfère des films des années 90 ou des années 2000)

On à plus qu'a recommander des films remplissant ces critères et qui on une note plus ou moins élevé.

#### On va dabord commencer par arrenger nos données

In [218]:
movies = movies_metadata[['title', 'genres', 'vote_count', 'vote_average', 'year', 'runtime']]
movies

,title,genres,vote_count,vote_average,year,runtime
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",5415.0,7.7,1995,81.0
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",2413.0,6.9,1995,104.0
2,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",92.0,6.5,1995,101.0
3,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",34.0,6.1,1995,127.0
4,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",173.0,5.7,1995,106.0
...,...,...,...,...,...,...
45461,Subdue,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",1.0,4.0,NaT,90.0
45462,Century of Birthing,"[{'id': 18, 'name': 'Drama'}]",3.0,9.0,2011,360.0
45463,Betrayal,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",6.0,3.8,2003,90.0
45464,Satan Triumphant,[],0.0,0.0,1917,87.0
45465,Queerama,[],0.0,0.0,2017,75.0

In [219]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         45460 non-null  object
 1   genres        45466 non-null  object
 2   vote_count    45460 non-null  float64
 3   vote_average  45460 non-null  float64
 4   year          45466 non-null  object
 5   runtime       45203 non-null  float64
dtypes: float64(3), object(3)
memory usage: 2.1+ MB

Dans la colonnes year je remplace toutes les valeurs null par des zéros pour pouvoir les convertir en int.

In [220]:
def convert_int(x):
    if x.isnumeric():
        return int(x)
    else :
        return 0

movies['year']= movies['year'].apply(convert_int)
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         45460 non-null  object
 1   genres        45466 non-null  object
 2   vote_count    45460 non-null  float64
 3   vote_average  45460 non-null  float64
 4   year          45466 non-null  int64
 5   runtime       45203 non-null  float64
dtypes: float64(3), int64(1), object(2)
memory usage: 2.1+ MB

<ipython-input-220-0e4a1def6055>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['year']= movies['year'].apply(convert_int)

On va maintenant traiter la colonne genres

In [221]:
movies['genres'][0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [222]:
from ast import literal_eval
a = "[1,2,3]"
b = literal_eval(a)
b

[1, 2, 3]

In [223]:
# On ramplce les valeurs manquantespar une chaine de caractère représentant une listes vides
movies['genres'] = movies['genres'].fillna('[]')
# Je passe mes chaine de caractère en listes 
movies['genres'] = movies['genres'].apply(literal_eval)
# Dans chaque dictionnaire contenue dans mes listes je récupère la valeur correspondant à la clés 'name'
movies['genres'] = movies['genres'].apply(
    lambda x: [i['name'].lower() for i in x] if isinstance(x, list) else [])

<ipython-input-223-63f2cf17b294>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].fillna('[]')
<ipython-input-223-63f2cf17b294>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].apply(literal_eval)
<ipython-input-223-63f2cf17b294>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].apply(

In [224]:
movies

,title,genres,vote_count,vote_average,year,runtime
0,Toy Story,"[animation, comedy, family]",5415.0,7.7,1995,81.0
1,Jumanji,"[adventure, fantasy, family]",2413.0,6.9,1995,104.0
2,Grumpier Old Men,"[romance, comedy]",92.0,6.5,1995,101.0
3,Waiting to Exhale,"[comedy, drama, romance]",34.0,6.1,1995,127.0
4,Father of the Bride Part II,[comedy],173.0,5.7,1995,106.0
...,...,...,...,...,...,...
45461,Subdue,"[drama, family]",1.0,4.0,0,90.0
45462,Century of Birthing,[drama],3.0,9.0,2011,360.0
45463,Betrayal,"[action, drama, thriller]",6.0,3.8,2003,90.0
45464,Satan Triumphant,[],0.0,0.0,1917,87.0
45465,Queerama,[],0.0,0.0,2017,75.0

In [158]:
# On fait disparaitre les genres
s = movies['genres'].apply(lambda x: pd.Series(x))
s = s.stack().reset_index(level=1, drop=True)
s.name = 'genre'
s

<ipython-input-158-ee3c40e9751f>:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s = movies['genres'].apply(lambda x: pd.Series(x))

0        animation
0           comedy
0           family
1        adventure
1          fantasy
           ...
45461       family
45462        drama
45463       action
45463        drama
45463     thriller
Name: genre, Length: 91106, dtype: object

In [159]:
gen_movies = movies.drop('genres', axis=1).join(s)

In [160]:
gen_movies

                  title  vote_count  vote_average  year  runtime      genre
0             Toy Story      5415.0           7.7  1995     81.0  animation
0             Toy Story      5415.0           7.7  1995     81.0     comedy
0             Toy Story      5415.0           7.7  1995     81.0     family
1               Jumanji      2413.0           6.9  1995    104.0  adventure
1               Jumanji      2413.0           6.9  1995    104.0    fantasy
...                 ...         ...           ...   ...      ...        ...
45463          Betrayal         6.0           3.8  2003     90.0     action
45463          Betrayal         6.0           3.8  2003     90.0      drama
45463          Betrayal         6.0           3.8  2003     90.0   thriller
45464  Satan Triumphant         0.0           0.0  1917     87.0        NaN
45465          Queerama         0.0           0.0  2017     75.0        NaN

[93548 rows x 6 columns]

#### Recommandation basé sur les connaissances

In [163]:
def recom_conn(gen_movies, percentile=0.80):
    genre = input("Entrez votre genre de film préféré : ")
    low_time = int(input("Saisissez la durée de film minimal : "))
    high_time = int(input("Saisissez la durée de film maximal : "))
    low_year = int(input("Saisissez l'année de film minimal : "))
    high_year = int(input("Saisissez l'année de film maximal : "))
    
    movies_reco = gen_movies.copy()
    
    movies_reco = movies_reco[(movies_reco['genre']==genre) &
                              (movies_reco['runtime']>=low_time) &
                              (movies_reco['runtime']<=high_time) &
                              (movies_reco['year']>=low_year) &
                              (movies_reco['year']<=high_year)
                             ]
    
    c = movies_reco['vote_average'].mean()
    m = movies_reco['vote_count'].quantile(percentile)
    
    q_film = movies_reco[(movies_reco['vote_count'] >= m)]
    
    q_film['score'] = q_film.apply(lambda x: (x['vote_count']/(x['vote_count']+m)*x['vote_average'])
                                   +(m/m+x['vote_count'])*c
                                   , axis=1)
    
    q_film = q_film.sort_values('score', ascending=False)
    q_film = q_film[['title', 'vote_count', 'vote_average', 'score', 'runtime']].head(30)
    
    return q_film

In [164]:
recom_conn(gen_movies)

Entrez votre genre de film préféré : action
Saisissez la durée de film minimal : 80
Saisissez la durée de film maximal : 120
Saisissez l'année de film minimal : 1990
Saisissez l'année de film maximal : 2020

<ipython-input-163-438cdb72fc0a>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q_film['score'] = q_film.apply(lambda x: (x['vote_count']/(x['vote_count']+m)*x['vote_average'])

,title,vote_count,vote_average,score,runtime
26564,Deadpool,11444.0,7.4,62177.055776,108.0
26553,Mad Max: Fury Road,9629.0,7.3,52317.767077,120.0
16974,Thor,6678.0,6.6,36287.049608,115.0
24455,Big Hero 6,6289.0,7.8,34175.133191,102.0
23358,Lucy,6048.0,6.3,32864.549521,89.0
26562,Ant-Man,6029.0,7.0,32762.016876,117.0
26568,Doctor Strange,5880.0,7.1,31952.732722,115.0
21130,World War Z,5683.0,6.7,30882.225263,116.0
24121,The Maze Runner,5540.0,7.0,30105.725862,113.0
24351,John Wick,5499.0,7.0,29883.010102,101.0
8234,The Incredibles,5290.0,7.4,28748.087540,115.0
11662,300,5092.0,7.0,27672.147268,117.0
6725,Kill Bill: Vol. 1,5091.0,7.7,27667.387971,111.0
23465,Edge of Tomorrow,4979.0,7.6,27058.896130,113.0
12217,I Am Legend,4977.0,6.9,27047.359714,101.0
21941,Thor: The Dark World,4873.0,6.8,26482.325189,112.0
19394,Looper,4777.0,6.6,25960.651557,118.0
19071,Brave,4760.0,6.7,25868.401668,93.0
15017,Kick-Ass,4747.0,7.1,25798.167697,117.0
23437,Maleficent,4607.0,7.0,25037.576706,97.0
1508,Men in Black,4521.0,6.9,24570.319508,98.0
17588,Rise of the Planet of the Apes,4452.0,7.0,24195.599344,105.0
12595,Taken,4444.0,7.2,24152.333578,93.0
18972,Men in Black 3,4228.0,6.3,22978.137514,106.0
3671,X-Men,4172.0,6.8,22674.415594,104.0
18723,21 Jump Street,4151.0,6.7,22560.245774,109.0
13635,X-Men Origins: Wolverine,4086.0,6.2,22206.681853,107.0
7917,"I, Robot",3889.0,6.7,21137.029014,115.0
17439,Drive,3832.0,7.4,20828.061861,100.0
5284,The Bourne Identity,3640.0,7.3,19784.995214,119.0

# 3. Recommandation basé sur la description
#### Cette fois ci on va fournir à notre algorithme un titre de filme et il va nous retourner les films qui lui sont similaires en se basant sur les descriptions (overview).

In [173]:
movies = movies_metadata[['id', 'title', 'genres', 'vote_count', 'vote_average', 'year', 'runtime', 'overview']]
def convert_int(x):
    if x.isnumeric():
        return int(x)
    else :
        return 0

movies['year']= movies['year'].apply(convert_int)

# On ramplce les valeurs manquantespar une chaine de caractère représentant une listes vides
movies['genres'] = movies['genres'].fillna('[]')
# Je passe mes chaine de caractère en listes 
movies['genres'] = movies['genres'].apply(literal_eval)
# Dans chaque dictionnaire contenue dans mes listes je récupère la valeur correspondant à la clés 'name'
movies['genres'] = movies['genres'].apply(
    lambda x: [i['name'].lower() for i in x] if isinstance(x, list) else [])

"""
# On fait disparaitre les genres
s = movies['genres'].apply(lambda x: pd.Series(x))
s = s.stack().reset_index(level=1, drop=True)
s.name = 'genre'
gen_movies = movies.drop('genres', axis=1).join(s)
gen_movies
"""

<ipython-input-173-5391d60b89bf>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['year']= movies['year'].apply(convert_int)
<ipython-input-173-5391d60b89bf>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].fillna('[]')
<ipython-input-173-5391d60b89bf>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].apply(literal_eval)
<ipython-input-173-5391d60b89bf>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].apply(

"\n# On fait disparaitre les genres\ns = movies['genres'].apply(lambda x: pd.Series(x))\ns = s.stack().reset_index(level=1, drop=True)\ns.name = 'genre'\ngen_movies = movies.drop('genres', axis=1).join(s)\ngen_movies\n"

#### On va vectoriser et appliquer la transformation TF-IDF sur la colonne 'overview'

In [185]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')

#On ramplace les NaN par une chaine vide
movies['overview'] = movies['overview'].fillna('')
# Vectorisation et trnasformation tf-idf des commentaires
tfidf_matrix = tfidf.fit_transform(movies['overview'])
tfidf_matrix.shape

<ipython-input-185-70f26d64d708>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['overview'] = movies['overview'].fillna('')

(45466, 75827)

#### Utilisation de la formule de similitude cosinus pour déterminer la similtude des films sur la base de leurs descriptions
<img src="img\cosine_sim.png" width="600">
Retourne un score compris entre -1 et 1. Plus le Score est élevé et plus les document sont similaire.

In [186]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [183]:
# Je construit une cartographie inverse des index et des titres des films, supprime les doublons
indices = pd.Series(movies.index, index=movies['title']).drop_duplicates()

In [184]:
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45461
Century of Birthing            45462
Betrayal                       45463
Satan Triumphant               45464
Queerama                       45465
Length: 45466, dtype: int64

#### Je crée ma fonction qui prend en entré le titre d'un film et retourne les recommandation

In [195]:
#exemple avec le film 'Jumanji' ayant l'indice 1
sim_scores = list(enumerate(cosin_sim[1]))
sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
# le film qui lui ressemble le plus d'unpoint de vue description est celui avec l'indice 21633.
sim_scores

[(1, 0.9999999999999999),
 (21633, 0.22806346875664207),
 (45253, 0.1913269216408526),
 (41573, 0.18912467206661468),
 (35509, 0.18884059289125973),
 (44376, 0.18711871153525655),
 (17223, 0.1794394926755732),
 (8801, 0.1779046935353395),
 (6166, 0.17716921373207242),
 (30981, 0.1711801085366708),
 (9503, 0.16935550376463201),
 (39938, 0.16479537817033266),
 (13601, 0.16397674075936416),
 (13711, 0.16006843321487454),
 (16843, 0.1577161703760495),
 (8079, 0.15449889748844933),
 (30398, 0.1525826691559911),
 (6055, 0.15189603271136512),
 (37271, 0.14949366203252104),
 (19726, 0.1482826519358981),
 (2486, 0.1467026491964079),
 (10892, 0.14633838986107717),
 (1506, 0.14369349131916645),
 (37447, 0.14295089108314576),
 (24049, 0.14043735690591996),
 (20492, 0.13943056531368167),
 (9107, 0.13804937671851011),
 (40321, 0.13793120540012999),
 (20067, 0.1367564583763373),
 (19345, 0.13515164029257928),
 (21723, 0.13323948855012455),
 (44037, 0.1328744432309908),
 (29024, 0.13246307139766694),
 (32028, 0.13093087072530146),
 (29599, 0.12962802558974135),
 (32973, 0.12914520548887023),
 (10703, 0.1287544298378342),
 (7749, 0.12841115185759047),
 (15512, 0.12680313659524856),
 (14166, 0.12563549999371856),
 (12726, 0.12490660081126796),
 (7906, 0.12460636288829119),
 (26381, 0.12306365555142401),
 (43993, 0.12283418138478443),
 (31666, 0.1225178503867575),
 (9369, 0.1217207054568494),
 (25296, 0.12120920174756789),
 (44727, 0.12108949282123209),
 (26462, 0.11987853445810251),
 (43500, 0.119232286851683),
 (5295, 0.11914591445397589),
 (43127, 0.11903501019617277),
 (3872, 0.11739951844507766),
 (25717, 0.11727215641428297),
 (21469, 0.11694543160441462),
 (34773, 0.11688231655009564),
 (39410, 0.11565283045576903),
 (41862, 0.11359768974131267),
 (24051, 0.11346220028282467),
 (8283, 0.1130095799270466),
 (10322, 0.11168048735813713),
 (5132, 0.11059428750785712),
 (11404, 0.11044253991103112),
 (23492, 0.10968286420743908),
 (31425, 0.10927963206964778),
 (17638, 0.1078258178002217),
 (3056, 0.10745943497897346),
 (19791, 0.10737742721866111),
 (6854, 0.10737031371087838),
 (8884, 0.10723405212081921),
 (40457, 0.10685840206724423),
 (19721, 0.10655370723407938),
 (18739, 0.10606202700211514),
 (33297, 0.10579286545080843),
 (44386, 0.10501586534729884),
 (30978, 0.10449371776635637),
 (35294, 0.10435648540917367),
 (39342, 0.10387777923976411),
 (24043, 0.10369595754724015),
 (6641, 0.10355445653685512),
 (19169, 0.10294145528411164),
 (8, 0.10253220357972959),
 (15871, 0.10239163216236075),
 (33007, 0.10175942196712161),
 (4083, 0.10155117488336501),
 (39709, 0.10123609182635457),
 (39675, 0.10055853040022186),
 (15518, 0.1003202780597712),
 (44940, 0.10016084133506574),
 (31662, 0.09992016238525683),
 (42134, 0.09905461263274234),
 (32891, 0.09904184555031945),
 (26453, 0.09895564094785703),
 (39198, 0.09861447486944586),
 (28063, 0.09855835753090025),
 (36787, 0.09855809898395546),
 (22243, 0.09833892246973085),
 (7805, 0.09833151549238166),
 (15793, 0.0979071706592702),
 (5717, 0.09779839038199362),
 (23753, 0.09765351818428594),
 (2249, 0.09756583933412277),
 (17879, 0.09739395276772256),
 (18775, 0.09697354641476476),
 (29657, 0.09675094847655082),
 (35181, 0.09667677035950296),
 (954, 0.09632385571555246),
 (30401, 0.09627176056453232),
 (29320, 0.09624913064029356),
 (24438, 0.09603231655808023),
 (363, 0.0960296697215355),
 (40664, 0.0957954030528981),
 (32733, 0.09578713769887719),
 (42772, 0.09548822756783142),
 (38001, 0.09542322171361227),
 (37085, 0.09473312125789),
 (21808, 0.09441035868257654),
 (33663, 0.0941243004764708),
 (9749, 0.09380711505843706),
 (21163, 0.09380615068692183),
 (22039, 0.09358229221595182),
 (20215, 0.09314856335507728),
 (18762, 0.09305140665665834),
 (38150, 0.09295297991622897),
 (35479, 0.09292014240726615),
 (22695, 0.09279019274737035),
 (34856, 0.0927218856396648),
 (27425, 0.09244412553692834),
 (44098, 0.09236212160432523),
 (28777, 0.09194258633507363),
 (22406, 0.091235839079074),
 (22938, 0.09116476228751579),
 (7663, 0.09107292781057316),
 (36424, 0.09086759838898036),
 (11342, 0.09080392776120887),
 (15765, 0.09080392776120887),
 (20090, 0.09047053123507418),
 (11220, 0.09044659488505676),
 (41506, 0.09044637996480306),
 (12838, 0.09035398430858184),
 (4652, 0.0900273430600251),
 (31835, 0.08992409954708688),
 (41861, 0.08988754453572881),
 (31676, 0.08987617597401906),
 (39344, 0.08955411474890454),
 (34131, 0.08932079853765328),
 (33660, 0.08917520572251685),
 (44851, 0.08908969768683857),
 (42024, 0.08890068043800452),
 (32377, 0.08889445682556305),
 (33882, 0.0888761976645683),
 (42307, 0.08883356208318881),
 (31816, 0.08871418248448507),
 (25028, 0.08870837754900436),
 (22825, 0.08868186685380204),
 (32595, 0.08856954667525849),
 (40896, 0.08818092600666343),
 (1951, 0.08818010476553129),
 (19839, 0.0881345042861087),
 (21777, 0.08813354739596371),
 (39463, 0.08791698344203334),
 (15067, 0.0878857625528061),
 (33045, 0.08783882636012351),
 (38403, 0.08777980039581168),
 (6417, 0.08759167935437702),
 (44803, 0.08758535703576113),
 (17936, 0.08732288420196828),
 (24757, 0.08709756368687077),
 (30304, 0.08703692916093275),
 (4217, 0.08701848994117606),
 (29497, 0.08698677871644274),
 (38928, 0.086980801184222),
 (6000, 0.08686856000394146),
 (6204, 0.08616715840080037),
 (32144, 0.08613801315656028),
 (14033, 0.08609749606940337),
 (15929, 0.08605305121719614),
 (10561, 0.08592758082392425),
 (42276, 0.08591165095508801),
 (32851, 0.0857048554112399),
 (32940, 0.08569791235598051),
 (7230, 0.08569204512037171),
 (16429, 0.08567636130044376),
 (1978, 0.08563434248344365),
 (26623, 0.08548022101492661),
 (28605, 0.08537938539166169),
 (4888, 0.08501380173538263),
 (40953, 0.0849978453689893),
 (45285, 0.0848218973111036),
 (45167, 0.08477138429253105),
 (10597, 0.08475321276728216),
 (5811, 0.08447174956761583),
 (26096, 0.08435949041545962),
 (5222, 0.08429540674438807),
 (5388, 0.08427310612890557),
 (42977, 0.08406942739110697),
 (21827, 0.08395221023532387),
 (976, 0.0838621051633153),
 (21715, 0.08338608407701237),
 (17305, 0.08331420205320536),
 (10211, 0.08326739913675606),
 (5823, 0.08323957836981975),
 (36071, 0.08307094366214064),
 (15386, 0.08295245296558883),
 (31467, 0.08287689577554487),
 (41753, 0.0826426940204813),
 (43999, 0.08263659003379355),
 (41205, 0.08247804796942478),
 (29679, 0.08240210780047344),
 (38012, 0.0822532490822271),
 (44591, 0.08225306050239661),
 (5454, 0.08182002055682211),
 (13858, 0.08164462405973508),
 (43798, 0.0816177018157405),
 (39390, 0.08134449274109672),
 (31322, 0.08128558963442506),
 (29445, 0.08124629225903247),
 (27215, 0.08118467251527732),
 (29043, 0.08112551868947916),
 (25077, 0.08096359343719219),
 (19160, 0.08095909152415699),
 (26584, 0.08093299501591068),
 (17260, 0.08079067292917813),
 (33023, 0.08069437637040316),
 (29011, 0.08060750130686034),
 (39478, 0.08048801864492597),
 (33825, 0.08047033871872229),
 (40415, 0.08040518894515856),
 (16054, 0.08020442632975423),
 (17579, 0.08018466351873228),
 (2331, 0.08015424456369571),
 (25791, 0.08009285495361307),
 (39155, 0.07982196827523144),
 (839, 0.0795006304763892),
 (43660, 0.07923798275811446),
 (18719, 0.07912735540691959),
 (22673, 0.07906226895472161),
 (12834, 0.07901844422328835),
 (21382, 0.07899714658335692),
 (10994, 0.07894025867290055),
 (22757, 0.07887436683400903),
 (11907, 0.07882991546237701),
 (36094, 0.07874365356541022),
 (23477, 0.07865537037817051),
 (5481, 0.07856512912557267),
 (11524, 0.0783477541737498),
 (21448, 0.07813973046554189),
 (17629, 0.07813078038892812),
 (31060, 0.07807856176521302),
 (27327, 0.0778478887756583),
 (33993, 0.07778251231309763),
 (1745, 0.07777004806845884),
 (39132, 0.07770160424463607),
 (44711, 0.07765294517191042),
 (8061, 0.07754887200150322),
 (8949, 0.07751502512714264),
 (23878, 0.07726677124908968),
 (33459, 0.07721942359845475),
 (15416, 0.07719176152150346),
 (26979, 0.07714813218661701),
 (40387, 0.07686088031865768),
 (894, 0.07686048061083534),
 (44814, 0.07678776090615318),
 (10527, 0.07678528548024914),
 (28281, 0.07669372736828212),
 (4084, 0.07663542816144829),
 (44862, 0.07662150149993764),
 (16538, 0.07649260462040082),
 (1611, 0.07638739199774677),
 (40228, 0.07608024630638133),
 (28034, 0.07592773842655345),
 (34044, 0.07588152372807005),
 (6588, 0.07585721725767723),
 (42932, 0.07581619389950682),
 (32827, 0.07578990678805073),
 (32414, 0.07556961578470134),
 (8437, 0.07551853920395259),
 (26815, 0.07549580309749332),
 (30172, 0.07525017022542047),
 (33672, 0.07507075946509871),
 (43335, 0.07506459904397597),
 (2421, 0.07501617039809554),
 (32579, 0.07492442686377303),
 (40432, 0.07492088737128563),
 (34073, 0.07486970913885461),
 (32605, 0.07485976116007795),
 (11538, 0.07478009393405365),
 (32820, 0.0747389793370361),
 (17064, 0.07467330539965475),
 (23161, 0.07462501074969957),
 (23431, 0.07449641526244681),
 (22560, 0.07438646626974571),
 (31619, 0.07416684650628419),
 (17081, 0.0741012348628002),
 (27166, 0.07407687692951404),
 (26579, 0.07403341597001249),
 (28628, 0.07397707157053514),
 (11173, 0.07396844799509907),
 (14847, 0.07392151795508883),
 (31036, 0.07382015259462195),
 (45259, 0.07381610273687812),
 (96, 0.07369839883298518),
 (27582, 0.07369473833237825),
 (27160, 0.07368603220257447),
 (41805, 0.07361149512332973),
 (14236, 0.07361009030636116),
 (5205, 0.07350347264706376),
 (22751, 0.07345334922199681),
 (34384, 0.07321199538476757),
 (29826, 0.07319568142533807),
 (11732, 0.07316994831795084),
 (29354, 0.07313165212753019),
 (12320, 0.07302216246069734),
 (39184, 0.07300161180398726),
 (7490, 0.0730000984347164),
 (41453, 0.07296161263724592),
 (29229, 0.07286710889966935),
 (24102, 0.07283098300101425),
 (33438, 0.07280424745038165),
 (3427, 0.07263727424302041),
 (16499, 0.0726202650614955),
 (19907, 0.07252853437251539),
 (19153, 0.0722893719475304),
 (43021, 0.07222591499535355),
 (15510, 0.0721953617334971),
 (26665, 0.07213677544219883),
 (9418, 0.07205678851847877),
 (30801, 0.07195977578397922),
 (11228, 0.07190223739322905),
 (33564, 0.071794701875337),
 (16109, 0.07167749289023041),
 (36753, 0.07161225646112529),
 (36241, 0.07156416980308522),
 (9301, 0.07141311035479272),
 (22276, 0.0712647212111512),
 (18650, 0.07120452807812806),
 (40015, 0.07108624724481179),
 (25091, 0.07106746539592479),
 (14246, 0.071018280426606),
 (21712, 0.07091168955047406),
 (7743, 0.07088654557718811),
 (3949, 0.07084938052598237),
 (23143, 0.070716022359299),
 (11745, 0.07069552490445541),
 (6260, 0.07064267124334854),
 (14073, 0.07061995562210754),
 (16867, 0.07051944946625432),
 (41656, 0.07050919835722276),
 (45301, 0.07040735119882541),
 (39831, 0.07024551840900131),
 (12995, 0.07005753674623678),
 (3809, 0.06983564572778156),
 (23128, 0.06983122592257826),
 (5712, 0.06977085070850629),
 (33764, 0.06966337427061002),
 (13817, 0.069527907104859),
 (39544, 0.06946917928683587),
 (11794, 0.0693915514310954),
 (23515, 0.06935036112924212),
 (21380, 0.0692008888971381),
 (34155, 0.06915826540858977),
 (20585, 0.06911717236176883),
 (38512, 0.0690883088320517),
 (9213, 0.06904799066761642),
 (1963, 0.06901196705627434),
 (44137, 0.06899906020501893),
 (25108, 0.06895879716101838),
 (27733, 0.06893758282337405),
 (31625, 0.0689207633586661),
 (7557, 0.06880412769816545),
 (309, 0.06876731713226888),
 (5073, 0.06869710435816882),
 (36539, 0.06865879661928793),
 (30846, 0.06865544338041538),
 (38151, 0.06860545424764142),
 (29848, 0.06842440422297459),
 (31114, 0.06841074909476486),
 (44946, 0.06835377354626991),
 (1970, 0.06833389891261185),
 (32743, 0.06829829071232663),
 (5055, 0.06825399519851262),
 (43918, 0.06824796840196316),
 (15568, 0.06813641780784783),
 (32106, 0.06809659179974484),
 (591, 0.06809071742707187),
 (20424, 0.06807785743411265),
 (39626, 0.06794071916854857),
 (268, 0.06782120869526216),
 (21922, 0.06767363330714891),
 (44354, 0.06757216410170791),
 (14756, 0.06747417550688335),
 (19039, 0.06742008375716685),
 (23187, 0.06730919072682826),
 (21295, 0.06727081446215508),
 (14882, 0.06726537160828652),
 (20334, 0.06725966284240086),
 (11955, 0.0672423051303784),
 (44485, 0.06711960286392918),
 (34346, 0.06709826004071232),
 (30931, 0.06698677885454286),
 (37267, 0.06694934179077962),
 (42766, 0.0668861707992643),
 (45462, 0.06687273390396511),
 (38900, 0.0668669829395645),
 (11904, 0.06669235772251503),
 (31711, 0.06666582295590369),
 (4095, 0.06661273066812168),
 (4094, 0.06661219352046435),
 (33024, 0.06659595853668987),
 (39900, 0.06654854138824517),
 (27378, 0.06654623440073673),
 (8808, 0.06653888425063052),
 (40542, 0.06644929174426796),
 (26034, 0.06644533971102708),
 (41438, 0.06643704867189888),
 (28987, 0.06643461567207867),
 (8845, 0.06639864609642657),
 (42288, 0.06635409407670227),
 (42335, 0.06633486062728565),
 (44427, 0.06623156826087953),
 (7673, 0.0662231829824655),
 (21648, 0.06621725266099439),
 (30771, 0.06614886770003756),
 (30546, 0.06603094300318717),
 (24263, 0.06602027845348343),
 (21743, 0.06599803301932558),
 (20443, 0.06597322331716471),
 (27243, 0.06586863146850314),
 (31475, 0.06585881510478638),
 (35356, 0.065819454021115),
 (36153, 0.06572269863308226),
 (14508, 0.06556916779832318),
 (24191, 0.06556702081375443),
 (29399, 0.06549233271832273),
 (27265, 0.06541863036948117),
 (30080, 0.0654135884029372),
 (30250, 0.0653704252876631),
 (14872, 0.0653195668710256),
 (10815, 0.0653092190205398),
 (9266, 0.06529703099607484),
 (2683, 0.06525976901245437),
 (3568, 0.06516907561525374),
 (22033, 0.06512967786585126),
 (2211, 0.06508846522733382),
 (15701, 0.06503954628090029),
 (29671, 0.06497148283453864),
 (41006, 0.06484176125449816),
 (30148, 0.06482876066696851),
 (5583, 0.06478821105754945),
 (43966, 0.06476085807905627),
 (41505, 0.06465599790841786),
 (32059, 0.06463820080419416),
 (12540, 0.06463148336930614),
 (8446, 0.06461589259097975),
 (19707, 0.0645911199590937),
 (26857, 0.06459023032124822),
 (2027, 0.0645621265357428),
 (16973, 0.06445960798979557),
 (16555, 0.0643621579758021),
 (34206, 0.06435853929728189),
 (15424, 0.06434759159417076),
 (44612, 0.06434072968622943),
 (34116, 0.06430969768790475),
 (25825, 0.06430141212768214),
 (34085, 0.06424776151576017),
 (44579, 0.0642331511675404),
 (12150, 0.06422572134560722),
 (19487, 0.06417096773641036),
 (1731, 0.06408165625731924),
 (42770, 0.06400361394599008),
 (5162, 0.06396423455435633),
 (21273, 0.06395235014633592),
 (32139, 0.06391212214983416),
 (39854, 0.063856421083046),
 (14908, 0.06381050027683044),
 (43360, 0.06376320098438468),
 (6388, 0.06375540116777385),
 (4333, 0.06372153085956819),
 (22704, 0.06369791008084802),
 (24040, 0.06356235241392477),
 (8853, 0.06353751758666837),
 (26393, 0.06351488184934474),
 (15237, 0.0634714468498835),
 (8290, 0.06341420210251432),
 (16405, 0.06337575411839572),
 (11763, 0.06331139874656613),
 (16490, 0.0631268550583746),
 (40600, 0.0630977847721936),
 (39481, 0.06305730465038112),
 (16087, 0.06301453681319877),
 (29223, 0.06286993781614524),
 (24176, 0.0628683250139813),
 (29968, 0.06283842139440711),
 (28262, 0.06281463978196168),
 (42450, 0.06276727673974085),
 (35131, 0.06275593601535705),
 (8612, 0.06249425655228379),
 (15902, 0.06248608317153367),
 (28426, 0.06241732335470355),
 (38690, 0.06238965414538122),
 (19367, 0.062344579456979424),
 (39183, 0.06227902866283212),
 (4530, 0.0622538482699847),
 (38189, 0.06219947723845888),
 (21652, 0.06217359949811621),
 (7029, 0.06214777288723731),
 (21896, 0.062115965707407926),
 (14043, 0.06206717531792992),
 (26629, 0.062011672343437484),
 (9684, 0.06198271265581243),
 (27242, 0.06196515703628467),
 (19301, 0.061887076169042966),
 (14384, 0.06181807542048477),
 (884, 0.061665154026831856),
 (3703, 0.06162553762827367),
 (4202, 0.061623991001193895),
 (14728, 0.06161929105766195),
 (20434, 0.06158561122509349),
 (17875, 0.0614578639044235),
 (32844, 0.06139847518350848),
 (10350, 0.061354858338006364),
 (13993, 0.06129141586703024),
 (717, 0.06127293066377702),
 (3003, 0.06125737856427998),
 (4556, 0.06124129824246132),
 (9305, 0.06123601179139537),
 (37687, 0.061212120073713114),
 (38205, 0.06118193432508208),
 (6736, 0.061170275848575956),
 (25672, 0.0611137668295498),
 (37882, 0.061053706860378774),
 (37962, 0.061052902992039304),
 (26364, 0.060997230279588394),
 (29893, 0.06094690343051181),
 (1603, 0.06093414163761251),
 (34389, 0.060893940982340355),
 (21261, 0.06070929918031944),
 (44472, 0.06070258338728227),
 (13275, 0.06065877727481738),
 (1071, 0.060635470363177096),
 (20153, 0.060618613165038526),
 (4823, 0.06060234007077299),
 (22256, 0.06052788651185153),
 (6939, 0.0605139230492573),
 (42047, 0.06048293849514845),
 (22022, 0.06048247168764535),
 (10353, 0.06046376643691989),
 (31017, 0.0604594238238007),
 (12740, 0.060293696823764655),
 (38418, 0.06026326951690067),
 (41592, 0.060227716721146365),
 (44094, 0.060203691115327536),
 (23108, 0.06018003746227254),
 (43218, 0.060115406587071284),
 (21068, 0.060086516233027146),
 (17682, 0.06002786217964468),
 (1996, 0.059948638887014974),
 (31003, 0.05991182212559176),
 (15145, 0.059867301970615246),
 (6709, 0.0598431533789974),
 (24860, 0.059763655225660656),
 (1275, 0.059753061334756885),
 (16906, 0.05970224109323791),
 (8214, 0.05969953863854118),
 (36418, 0.05969785249467978),
 (23404, 0.05968421182640242),
 (9621, 0.059660295292278315),
 (9583, 0.059632064900882215),
 (22854, 0.05961634913133152),
 (44140, 0.05960744571806629),
 (42186, 0.059589187192771745),
 (15173, 0.05956576464031725),
 (3576, 0.05956358085430204),
 (7184, 0.05955180488978451),
 (8230, 0.05942641621894646),
 (20415, 0.05936535210967892),
 (19979, 0.05933723136330754),
 (5190, 0.05930587545336678),
 (39252, 0.059264530631453566),
 (3475, 0.05924860698676506),
 (23695, 0.059173259323710085),
 (30118, 0.05910497881359841),
 (2396, 0.05905103940992727),
 (15994, 0.059040411164183515),
 (22918, 0.05901754174096576),
 (43139, 0.058993602036104056),
 (14522, 0.05893270779928785),
 (42837, 0.05891662429914621),
 (19129, 0.058916349146365544),
 (41963, 0.05891227627649968),
 (29453, 0.058728952997605714),
 (1672, 0.05870102704341262),
 (36926, 0.05865367525148624),
 (26350, 0.058644995341296656),
 (18865, 0.058398625186544526),
 (43090, 0.058252947854653875),
 (33585, 0.05822976798249082),
 (27405, 0.058152386824879866),
 (31937, 0.058122379143462424),
 (2679, 0.05809594431165935),
 (27698, 0.058081603750478196),
 (21868, 0.05803733523844437),
 (17625, 0.05803312659007419),
 (29678, 0.058030455671288776),
 (44614, 0.058014432396862464),
 (40412, 0.05797231385151725),
 (28382, 0.057936418952952345),
 (39793, 0.0578718865646404),
 (45338, 0.057850930961100756),
 (32953, 0.05779234117339626),
 (27909, 0.05778624876928438),
 (24427, 0.05776685409030317),
 (16442, 0.057748308834988535),
 (30336, 0.05771704332947451),
 (8210, 0.057592646491330564),
 (11504, 0.05756154780072037),
 (43504, 0.05752606191606781),
 (10550, 0.0575174418614703),
 (20720, 0.057473158228854626),
 (11929, 0.057470767690574354),
 (4013, 0.05746423642261952),
 (2760, 0.05744903877169203),
 (41409, 0.05732745467574335),
 (40757, 0.05729255057610421),
 (5763, 0.0572540966564135),
 (13985, 0.05719387762918547),
 (32161, 0.057144385273795215),
 (44124, 0.05709698578087138),
 (44860, 0.05706289116094294),
 (18107, 0.057054433012857765),
 (14379, 0.05703609654766187),
 (2067, 0.05699789624476237),
 (18591, 0.05695860814009273),
 (41101, 0.056947813159802775),
 (9216, 0.056925305457051496),
 (32117, 0.05678974773963086),
 (39911, 0.05678186343742249),
 (32042, 0.0567600779822413),
 (25780, 0.05671017164314654),
 (17651, 0.05670610612233602),
 (39578, 0.05666163059723402),
 (13029, 0.056584560029715576),
 (35519, 0.056570582988879306),
 (31230, 0.056505128380687136),
 (22514, 0.056493691569513886),
 (22242, 0.05639786331110993),
 (13901, 0.05620497936206023),
 (21760, 0.0561696156513366),
 (184, 0.05615732312236105),
 (2678, 0.05613598412560222),
 (17906, 0.056120479284176676),

In [199]:
# Je met tout ça en fonction pour que tout cela soit plus propre
def recom_con(title, cosine_sim=cosine_sim, movies=movies, indices=indices):
    # Je récupère l'indice du film
    idx = indices[title]
    # Je récupère tout les score de similitude du film concerné avec tout les films 
    sim_scores = list(enumerate(cosin_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    # Je récupère l'indice des 10 films les plus proches
    sim_scores = sim_scores[1:11]
    movies_indices = [i[0] for i in sim_scores]
    return movies['title'].iloc[movies_indices]

In [200]:
recom_con('The Lion King')

34682    How the Lion Cub and the Turtle Sang a Song
9353                                The Lion King 1½
9115                  The Lion King 2: Simba's Pride
42829                                           Prey
25654                                 Fearless Fagan
17041                                   African Cats
27933              Massaï, les guerriers de la pluie
6094                                       Born Free
37409                                     Sour Grape
3203                                The Waiting Game
Name: title, dtype: object

In [201]:
recom_con('Jumanji')

21633         Table No. 21
45253                 Quiz
41573         Snowed Under
35509             The Mend
44376    Liar Game: Reborn
17223       The Dark Angel
8801               Quintet
6166             Brainscan
30981         Turkey Shoot
9503             Word Wars
Name: title, dtype: object