In [12]:
import pandas as pd 

data = pd.read_excel("jeux_donnees/Data_Professional_Salary_Survey_Responses_1.xlsx")

In [13]:
data.dtypes

Survey Year                                      int64
Timestamp                               datetime64[ns]
SalaryUSD                                      float64
Country                                         object
PostalCode                                      object
PrimaryDatabase                                 object
YearsWithThisDatabase                            int64
OtherDatabases                                  object
EmploymentStatus                                object
JobTitle                                        object
ManageStaff                                     object
YearsWithThisTypeOfJob                           int64
HowManyCompanies                                object
OtherPeopleOnYourTeam                           object
CompanyEmployeesOverall                         object
DatabaseServers                                 object
Education                                       object
EducationIsComputerRelated                      object
Certifications                                  object
HoursWorkedPerWeek                              object
TelecommuteDaysPerWeek                          object
NewestVersionInProduction                       object
OldestVersionInProduction                       object
PopulationOfLargestCityWithin20Miles            object
EmploymentSector                                object
LookingForAnotherJob                            object
CareerPlansThisYear                             object
Gender                                          object
OtherJobDuties                                  object
KindsOfTasksPerformed                           object
Counter                                          int64
dtype: object

In [27]:
# Pour connaitre le 

for i in data.columns :
    print("###",i,"###")
    #print(data[i].value_counts())
    l = list(data[i])
    l = map(str, l)
    length = map(len,l)
    print(max(length))
    print("\n")

### Survey Year ###
4


### Timestamp ###
26


### SalaryUSD ###
9


### Country ###
22


### PostalCode ###
20


### PrimaryDatabase ###
23


### YearsWithThisDatabase ###
5


### OtherDatabases ###
210


### EmploymentStatus ###
65


### JobTitle ###
106


### ManageStaff ###
3


### YearsWithThisTypeOfJob ###
4


### HowManyCompanies ###
66


### OtherPeopleOnYourTeam ###
11


### CompanyEmployeesOverall ###
12


### DatabaseServers ###
9


### Education ###
26


### EducationIsComputerRelated ###
9


### Certifications ###
32


### HoursWorkedPerWeek ###
9


### TelecommuteDaysPerWeek ###
33


### NewestVersionInProduction ###
79


### OldestVersionInProduction ###
48


### PopulationOfLargestCityWithin20Miles ###
20


### EmploymentSector ###
37


### LookingForAnotherJob ###
40


### CareerPlansThisYear ###
46


### Gender ###
23


### OtherJobDuties ###
389


### KindsOfTasksPerformed ###
152


### Counter ###
1